# Generated by Django 2.2.12 on 2022-04-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='title',
        ),
        migrations.AddField(
            model_name='specialization',
            name='special',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], default='1', max_length=20),
        ),
    ]
