# Generated by Django 2.2.12 on 2022-04-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac_app', '0002_auto_20220414_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='Media/'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='special',
            field=models.CharField(choices=[('1', 'IT'), ('2', 'CS'), ('3', 'MACHNICAL'), ('4', 'ELICTRICAL')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(choices=[('1', 'PHY'), ('2', 'CHE'), ('3', 'MATH'), ('4', 'ENGLISH')], default='1', max_length=20),
        ),
    ]
