# Generated by Django 2.2.12 on 2022-04-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac_app', '0004_auto_20220415_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fac_app.Type'),
        ),
    ]
