# Generated by Django 2.2.12 on 2022-04-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac_app', '0005_faculty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='fac_app.Specialization'),
        ),
    ]
